"use strict";
exports.__esModule = true;
var rotation_service_1 = require("./rotation.service");
var jpeg = require("jpeg-js");
var sizeOf = require("image-size");
var img = require('./test_image');
var jpeg_data = Buffer.from(img, "base64");
var raw_image_data = jpeg.decode(jpeg_data);
var dimensions = sizeOf(raw_image_data);
var buf = new Uint8ClampedArray(new ArrayBuffer(raw_image_data));
var to_rotate = new ImageData(dimensions.width, dimensions.height);
to_rotate.data.set(buf);
var rotationService = new rotation_service_1.RotationService();
var start = performance.now();
var rotated = rotationService.rotate(to_rotate, 88);
var end = performance.now();
console.log("Rotate Operation Completed in " + (end - start) + " ms");
console.log("__________________________________________________");
console.log("Old Dimensions : h " + dimensions.height + ", w " + dimensions.width);
console.log("New Dimensions : h " + rotated.height + ", w " + rotated.width);
